theme: "hugo-PaperMod"
baseURL: "https://slack-overflow-help.netlify.app/"
languageCode: en-gb
title: Slack Overflow tips & tricks
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  author: Jamie Hudson
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 100
    threshold: 0
    minMatchCharLength: 0
    keys: ["title", "content"]
  
  label:
    text: "Slack Overflow"
    icon: /logo.png
    iconHeight: 50 
  
    
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  
  homeInfoParams:
    Title: "Welcome fellow data lovers \U0001F44B"
    Content:   >
          This website acts as a repository for tutorials and documentation that have been spawned from conversation and questions on the **\#slack_overflow** Slack Channel.
          
          
          Know what you are looking for? Browse documents based on relevant `R Packages`, Tags, or manually search for the tutorial you are looking for using the buttons above ☝..


          See below for the most recent documentation 👇. 
          
          
menu:
  main:
    - identifier: R_packages
      name: R packages
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 30
    - identifier: slack_overflow
      name: slack_overflow
      url: https://sharecreative.slack.com/archives/C03FEC4C33N
      weight: 40
      
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

